// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package controllers

// Injectors from wire.go:

func InitializeRootController() (*RootController, error) {
	authController := NewAuthController()
	rootController := NewRootController(authController)
	return rootController, nil
}
